### ISSUE TITLE
Cannot assign more than one switch to a delegate

### ISSUE THREAD

**Issue by jonlange** [Cookiezby/LabelSwitch#10]
Correct me if I'm wrong, but in the current implementation it is impossible to distinguish which LabelSwitch has changed state. For example if I have 3 switches in the view and assign the same delegate for each, I will not be able to determine which switch triggered the event. Can you return the LabelSwitch that triggered the event via the delegate?

**Comment by Cookiezby** [comment]
@jonlange sorry to reply so late, I have not realize such situation, Did you try to set the tag of the view?  so you can recognize which switch is triggered by the tag?

**Comment by Cookiezby** [comment]
I have update the delegate in v0.1.6, hope it helps you @jonlange
