### ISSUE TITLE
Version 0.1.6 is not working with CocoaPods

### ISSUE THREAD

**Issue by jonlange** [Cookiezby/LabelSwitch#12]
I see that you made a release, but the version is not available in CocoaPods

![screen shot 2019-02-15 at 12 40 36 pm](https://user-images.githubusercontent.com/5024665/52880418-279f2880-311f-11e9-8d30-225374f47cd0.png)

**Comment by Cookiezby** [comment]
@jonlange  
Hi, you can run these script to get the update.
```
pod repo update 
pod update
```
