### ISSUE TITLE
Allow option to disable switch

### ISSUE THREAD

**Issue by JoshHrach** [Cookiezby/LabelSwitch#13]
Native iOS interactive elements, like the UISwitch, inherit from UIControl, which allows them to be disabled. While your LabelSwitch likely can't inherit from UIControl, it would be nice if there was an option to disable the switch to prevent interaction. A couple of use cases:

* A switch triggers a network request. You could disable the switch while the request is active to prevent switch updates by the user.
* A switch is used to determine the user's choice of a feature or service that might not be eligible to them. Thus, you would want to disable the switch so they can't use it.

**Comment by Cookiezby** [comment]
0.1.7 has already add isEnable  property.
