### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [Cookiezby/LabelSwitch#2]
Good day @Cookiezby , I am Tobaloidee and i am a graphics designer. I want to contribute here in your project by designing a logo for it which i will be doing for free. With your permission i will start my design and show you here asap. Thanks! - Tobaloidee

**Comment by Cookiezby** [comment]
Of cause you can do it, I am very glad that you'd like to help with that! @Tobaloidee

**Comment by Tobaloidee** [comment]
Hi Sir here's what i came up with! I hope you will like it..

concept: letters L & S incorporated with the switch symbol to form a modern and minimal icon which is visible in small sizes and memorable

FAVICON
![ls-01](https://user-images.githubusercontent.com/36028424/41541172-6d7c2d74-7344-11e8-947d-a863f5c55ff2.png)

LOGOTYPES
![ls-02](https://user-images.githubusercontent.com/36028424/41541189-738548fe-7344-11e8-8dab-9586386c31a5.png)

COLOR OPTIONS
![ls-03](https://user-images.githubusercontent.com/36028424/41541200-78dea638-7344-11e8-8261-e580f78593da.png)

**Comment by Cookiezby** [comment]
Nice job,  I will update the Readme later, Thanks for your work!

**Comment by Tobaloidee** [comment]
I can put it in Readme thru PR also Sir if you let me..

**Comment by Tobaloidee** [comment]
Which color do you prefer?

**Comment by Tobaloidee** [comment]
Okay..thanks a lot! Will finalize the files and make a PR later sir.

**Comment by Tobaloidee** [comment]
Here's the PR #3 with the logo file upload and readme update..Thanks and best regards! 

-Tobaloidee
