### ISSUE TITLE
Use of unimplemented initializer 'init(frame:)' for class 'LabelSwitch.LabelSwitch'

### ISSUE THREAD

**Issue by KheniDharmesh** [Cookiezby/LabelSwitch#8]
Getting this error at 

> ~/Library/Logs/DiagnosticReports

**Comment by Cookiezby** [comment]
Thanks for you report, I will check this weekend

**Comment by KheniDharmesh** [comment]
Thanks

**Comment by Cookiezby** [comment]
LabelSwitch does not implement the init(frame:) initialization, so just use the initialization in the README. @KheniDharmesh

**Comment by n1schal** [comment]
@Cookiezby the readme suggests it can be set from storyboard, but this issue comes up when doing so. Is initializing with switch = LabelSwitch(text, ls, rs) the only way to make it work then? I don't think doing that is very convenient.
